### ISSUE TITLE
Please add a license file to this repo

### ISSUE THREAD

**Issue by jon-garner** [LTLA/umappp#6]
Thank you for sharing this repo with us!

Could you please add an explicit LICENSE file to the repo so that it's clear
under what terms the content is provided, and under what terms user
contributions are licensed?

[GitHub docs on licensing](https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license)

> However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

Thanks!

**Comment by LTLA** [comment]
Hm. Well, it's not that I don't want to, but navigating the licensing of all the upstream works is a bit tricky. IIRC the original Python implementation was BSD-3 (?), but I wrote most of this code based on stuff from **uwot**, which is GPL-3.

IANAL but I guess that makes **umappp** GPL-3 as well.

Tagging @jlmelville if he has thoughts on this, otherwise I'll just slap the GPL-3 license in here later today.

**Comment by jlmelville** [comment]
Uwot is GPL-3 only because to integrate with R I must include Rcpp headers which therefore requires the *R package as a whole* to be licensed as GPL. However the non-R-binding C++  code (anything in the `uwot` namespace) is licensed as BSD 2-clause and should say as much in every header file (please let me know if I missed one). I am usually better about specifying the vagaries of the licensing of the bindings vs the underlying library that is being wrapped so I should update the README. Sorry for any confusion.

**Comment by LTLA** [comment]
Sounds good enough to me - added BSD-2 in 555bb77543037b4d63eda027550e48cda89590dd.
